# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TkYjOPz13EVDM6ZNiM79db7F-B--dU1V
"""

from github import Github

TOKEN ="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"

g = Github(TOKEN)

repo_url = input("GitHub Repository URL: ")

parts = repo_url.rstrip("/").split("/")

owner = parts[-2]
repo_name = parts[-1]

repo = g.get_repo(f"{owner}/{repo_name}")

print("\n===== Repository Info =====")
print("Name:", repo.name)
print("Owner:", repo.owner.login)
print("Stars:", repo.stargazers_count)
print("Forks:", repo.forks_count)
print("Open Issues:", repo.open_issues_count)
print("Language:", repo.language)